### ISSUE TITLE
Installing transit-python fails when specifying "--no-use-wheel"

### ISSUE THREAD

**Issue by jashugan** [cognitect/transit-python#24] opened 2016-01-13 19:52 UTC
We have problem installing certain packages using wheels, so we install all of our packages from source. When trying to do the same with transit-python, it fails, because you inexplicably have code that tries to get the revision in your `setup.py` file. I think I've mentioned this before, but you really should _not_ be doing that. For one solution of the proper way to do this, take a look at https://github.com/mitsuhiko/flask/blob/master/scripts/make-release.py.

Here's the error:

```
(weblims)[~/projects/locus-web-lims](git:pacbio-confirmation!)$ pip install --no-use-wheel transit-python
Downloading/unpacking transit-python
  http://build.locusdev.net:10001/simple/transit-python/ uses an insecure transport scheme (http). Consider using https if build.locusdev.net:10001 has it available
  Downloading transit-python-0.8.250.tar.gz
  Storing download in cache at /Users/nithin/.pip/cache/http%3A%2F%2Fbuild.locusdev.net%3A10001%2Fpackages%2Ftransit-python-0.8.250.tar.gz
  Running setup.py (path:/Users/nithin/.virtualenvs/weblims/build/transit-python/setup.py) egg_info for package transit-python
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/nithin/.virtualenvs/weblims/build/transit-python/setup.py", line 19, in <module>
        revision = subprocess.check_output("./bin/revision")
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command './bin/revision' returned non-zero exit status 128
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/nithin/.virtualenvs/weblims/build/transit-python/setup.py", line 19, in <module>

    revision = subprocess.check_output("./bin/revision")

  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command './bin/revision' returned non-zero exit status 128

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/nithin/.virtualenvs/weblims/build/transit-python
Storing debug log for failure in /Users/nithin/.pip/pip.log
```

**Comment by benkamphaus** [comment] 2016-01-13 21:07
This is a duplicate of https://github.com/cognitect/transit-python/issues/17

**Closed by benkamphaus** 2016-01-13 21:07 UTC
Labels: duplicate

**Comment by benkamphaus** [comment] 2016-02-26 18:52
Release [0.8.282](https://groups.google.com/d/msg/transit-format/AJwXyroqP_8/YsPflrkLGwAJ) includes a fix for this (mentioned on other thread also).

**Comment by jashugan** [comment] 2016-03-05 06:18
Thanks!
